apiVersion: apps/v1
kind: Deployment
metadata:
  name: radish-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: radish-backend
  template:
    metadata:
      labels:
        app: radish-backend
    spec:
      containers:
        - name: radish-backend-container
          image: your_docker_registry/com.example.demo/radish-backend:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "0.5"
              memory: "512Mi"

---

apiVersion: v1
kind: Service
metadata:
  name: radish-backend-service
spec:
 type: ClusterIP
  selector:
    component: rest-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
